version: '3.4'

services:
    grobid:
        build:
            context: .
            dockerfile: Dockerfile
            target: ${GROBID_VARIANT_NAME}
        image: elifesciences/sciencebeam-grobid-biorxiv:${IMAGE_TAG}${GROBID_IMAGE_TAG_SUFFIX:-}
        ports:
            - "${GROBID_PORT:-8070}:8070"
        extra_hosts:
            - github.com:127.0.0.1
