FROM elifesciences/sciencebeam-trainer-delft-grobid_unstable:04346b26b5fa7966cef4d6ec6bba867feba52d66-dee3b060495006aa9f8e1b89f6278b44231fe0cc

ENV GROBID_MODELS_DIRECTORY=/opt/grobid/grobid-home/models
ENV GROBID__CRF__ENGINE=wapiti
ENV GROBID__HEADER__USE_HEURISTICS=false
ENV GROBID__FEATURES__REMOVE_LINE_NUMBERS=true

HEALTHCHECK --interval=10s --timeout=10s \
  CMD curl --fail http://localhost:8070 || exit 1
