FROM elifesciences/sciencebeam-trainer-delft-grobid_unstable:04346b26b5fa7966cef4d6ec6bba867feba52d66-dee3b060495006aa9f8e1b89f6278b44231fe0cc

ENV GROBID_MODELS_DIRECTORY=/opt/grobid/grobid-home/models

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "segmentation=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/wapiti-grobid-segmentation-biorxiv-2020-06-01.tar.gz" \
    --validate-pickles

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "header=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/wapiti-grobid-header-biorxiv-2020-06-01.tar.gz" \
    --validate-pickles

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "reference-segmenter=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/wapiti-grobid-reference-segmenter-biorxiv-2020-06-01.tar.gz" \
    --validate-pickles

ENV GROBID__CRF__ENGINE=wapiti
ENV GROBID__FEATURES__REMOVE_LINE_NUMBERS=true

HEALTHCHECK --interval=10s --timeout=10s \
  CMD curl --fail http://localhost:8070 || exit 1
