FROM elifesciences/sciencebeam-trainer-delft-grobid_unstable:04346b26b5fa7966cef4d6ec6bba867feba52d66-dee3b060495006aa9f8e1b89f6278b44231fe0cc

ENV GROBID_MODELS_DIRECTORY=/opt/grobid/grobid-home/models
ENV EMBEDDING_REGISTRY_PATH="${PROJECT_FOLDER}/embedding-registry.json"

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "segmentation=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/delft-grobid-segmentation-biorxiv-glove-6b-50d-2020-05-22.tar.gz" \
    --validate-pickles

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "header=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/delft-grobid-header-biorxiv-glove-6b-50d-2020-05-22.tar.gz" \
    --validate-pickles

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "reference-segmenter=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/delft-grobid-reference-segmenter-biorxiv-glove-6b-50d-2020-05-22.tar.gz" \
    --validate-pickles

RUN python -m sciencebeam_trainer_delft.embedding \
    override-embedding-url \
    --registry-path="${EMBEDDING_REGISTRY_PATH}" \
    --override-url="glove.6B.50d=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/glove.6B.50d.mdb.xz"

RUN python -m sciencebeam_trainer_delft.embedding \
    preload \
    --registry-path="${EMBEDDING_REGISTRY_PATH}" \
    --embedding="glove.6B.50d"

ENV GROBID__CRF__ENGINE=wapiti
ENV GROBID__CRF__ENGINE__SEGMENTATION=delft
ENV GROBID__CRF__ENGINE__HEADER=delft
ENV GROBID__CRF__ENGINE__REFERENCE_SEGMENTER=delft
ENV GROBID__FEATURES__REMOVE_LINE_NUMBERS=true

HEALTHCHECK --interval=10s --timeout=10s \
  CMD curl --fail http://localhost:8070 || exit 1
