ARG base_image
FROM ${base_image}

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "segmentation=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/2020-10-04-delft-grobid-segmentation-biorxiv-no-word-embedding-text-feature.tar.gz" \
    --validate-pickles

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "header=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/2020-10-04-delft-grobid-header-biorxiv-no-word-embedding.tar.gz" \
    --validate-pickles

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "affiliation-address=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/2020-10-04-delft-grobid-affiliation-address-biorxiv-no-word-embedding.tar.gz" \
    --validate-pickles

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "reference-segmenter=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/2020-10-04-delft-grobid-reference-segmenter-biorxiv-no-word-embedding.tar.gz" \
    --validate-pickles

RUN python -m sciencebeam_trainer_delft.sequence_labelling.tools.install_models \
    --model-base-path=${GROBID_MODELS_DIRECTORY} \
    --install "citation=https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/2020-10-04-wapiti-grobid-citation-biorxiv.tar.gz" \
    --validate-pickles

ENV GROBID__CRF__ENGINE__SEGMENTATION=delft
ENV GROBID__CRF__ENGINE__HEADER=delft
ENV GROBID__CRF__ENGINE__AFFILIATION_ADDRESS=delft
ENV GROBID__CRF__ENGINE__REFERENCE_SEGMENTER=delft
ENV GROBID__CRF__ENGINE__CITATION=wapiti
