version: '3'

services:
    grobid:
        build:
            context: .
            dockerfile: ${GROBID_DOCKERFILE:-Dockerfile}
        image: elifesciences/sciencebeam-grobid-biorxiv:${IMAGE_TAG}${GROBID_IMAGE_TAG_SUFFIX:-}
        ports:
            - "${GROBID_PORT:-8070}:8070"
